#spring.application.name=todo

server:
  port: 8081
  #8080 è quella di defaul,ma andrebbr in conflitto con php
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/java?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    #java databaseconnection= jdbc => sono librerie ; chiamate che bisogna gestire
    #utilizziamo i driver di mysql => mysql implements jdbc
    username: java
    password: java
  jpa:
    #vogliamo leggere sql. salva automaticamente il database senza fare query
    show-sql: true
    hibernate:
      ddl-auto: update
      #se la tabella ha bisogno di fare un update lo fa

      #properties=> usare i dialetti di mysql

